services:
  - type: web
    name: insomnia-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10004"
    envVars:
      - key: PORT
        value: 10004
